Vagrant.configure("2") do |config|
  config.vm.hostname = "front"
  config.vm.box = "centos/7"
  config.vm.network "private_network", ip: "192.168.1.3"
  config.vm.provision :shell, path: "../provisions/docker-grafana.sh"
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  end