Vagrant.configure("2") do |config|
  config.vm.hostname = "controle"
  config.vm.box = "centos/7"
  config.vm.network "private_network", ip: "192.168.1.4"
  config.vm.provision :shell, path: "../provisions/ansible.sh"
end